#define WIFI_SSID "your-wifi-ssid"
#define WIFI_SECRET "your-wifi-secret"
#define API_URL "your-https-api-url"
#define AUTH_USER "your-http-basic-auth-username"
#define AUTH_PASS "your-http-basic-auth-password"
